name: Deploy Vite App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install  # Ensure dependencies are installed

      - name: Inject Environment Variables
        run: echo "VITE_OPENAI_API_KEY=${{ secrets.VITE_OPENAI_API_KEY }}" >> .env

      - name: Debug .env file
        run: cat .env  # Debugging step to verify the API key is correctly injected

      - run: npm run build

      - name: Clean dist directory (remove any exposed secrets)
        run: rm -rf dist/assets/index-*.js  # Example cleanup step if needed

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
